services:
  app:
    platform: linux/amd64
    ports:
      - "3000:8080"
    build: .
    environment:
      - PORT=8080
    env_file:
      - .env
      - .env.local
    container_name: servicemap-ui
