# Don't allow dependencies to be used before they have been released for at least 1 week
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@remix-run/router@1.23.3'
  - 'react-router@6.30.4'
  - 'baseline-browser-mapping@2.10.40'
  - 'caniuse-lite@1.0.30001800'
  - 'electron-to-chromium@1.5.384'

# Hoist all dependencies to the root of node_modules, for better compatibility with packages that expect flat node_modules
shamefullyHoist: true

overrides:
  '@typescript-eslint/typescript-estree>minimatch': '9.0.7'
  esbuild: '^0.28.1'
  '@opentelemetry/core@^2': '^2.8.0'

allowBuilds:
  '@sentry/cli': true
  core-js: false
  esbuild: true
