# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PORT: 2048
      SSR_FETCH_TIMEOUT: 2500
      ACCESSIBILITY_SENTENCE_API: https://www.hel.fi/palvelukarttaws/rest/v4
      SERVICEMAP_API: https://api.hel.fi/servicemap/v2
      EVENTS_API: https://api.hel.fi/linkedevents/v1
      RESERVATIONS_API: https://api.hel.fi/respa/v1
      PRODUCTION_PREFIX: SM
      DIGITRANSIT_API: https://api.digitransit.fi/routing/v1/routers/hsl/index/graphql
      FEEDBACK_URL: https://api.hel.fi/servicemap/open311/
      HEARING_MAP_API: https://kuulokuvat.fi/api/v1/servicemap-url
      MODE: production
      CITIES: helsinki,espoo,vantaa,kauniainen,kirkkonummi
      SERVICE_MAP_URL: https://tiles.hel.ninja/styles/hel-osm-bright/{z}/{x}/{y}
      ACCESSIBLE_MAP_URL: https://tiles.hel.ninja/styles/turku-osm-high-contrast-pattern/{z}/{x}/{y}
      ORTOGRAPHIC_MAP_URL: https://kartta.hsy.fi/geoserver/gwc/service/wmts?layer=taustakartat_ja_aluejaot:Ortoilmakuva_2019&tilematrixset=ETRS-GK25&Service=WMTS&Request=GetTile&Version=1.0.0&TileMatrix=ETRS-GK25:{z}&TileCol={x}&TileRow={y}&Format=image%2Fpng
      ORTOGRAPHIC_WMS_URL: "https://kartta.hsy.fi/geoserver/wms"
      ORTOGRAPHIC_WMS_LAYER: "taustakartat_ja_aluejaot:Ortoilmakuva_2019"
      GUIDE_MAP_URL: https://kartta.hel.fi/ws/geoserver/avoindata/gwc/service/wmts?layer=avoindata:Karttasarja_PKS&tilematrixset=ETRS-GK25&Service=WMTS&Request=GetTile&Version=1.0.0&TileMatrix=ETRS-GK25:{z}&TileCol={x}&TileRow={y}&Format=image%2Fpng

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run testBuild
    - run: npm test
    - run: npm run browserTestCLI
