# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/ci-node.yml@main
    secrets: inherit
    with:
      node-version: 22.x
      extra-commands: |
        echo "PORT=2048" >> $GITHUB_ENV
        echo "SSR_FETCH_TIMEOUT=2500" >> $GITHUB_ENV
        echo "ACCESSIBILITY_SENTENCE_API=https://www.hel.fi/palvelukarttaws/rest/v4" >> $GITHUB_ENV
        echo "SERVICEMAP_API=https://api.hel.fi/servicemap/" >> $GITHUB_ENV
        echo "SERVICEMAP_API_VERSION=v2" >> $GITHUB_ENV
        echo "EVENTS_API=https://api.hel.fi/linkedevents/v1" >> $GITHUB_ENV
        echo "RESERVATIONS_API=https://varaamo.hel.fi" >> $GITHUB_ENV
        echo "PRODUCTION_PREFIX=SM" >> $GITHUB_ENV
        echo "DIGITRANSIT_API=https://digitransit-proxy.api.hel.fi/routing/v1/routers/hsl/index/graphql" >> $GITHUB_ENV
        echo "FEEDBACK_URL=https://api.hel.fi/servicemap/open311/" >> $GITHUB_ENV
        echo "HEARING_MAP_API=https://kuulokuvat.fi/api/v1/servicemap-url" >> $GITHUB_ENV
        echo "MODE=production" >> $GITHUB_ENV
        echo "CITIES=helsinki,espoo,vantaa,kauniainen,kirkkonummi" >> $GITHUB_ENV
        echo "ORGANIZATIONS=[{ \"id\": \"83e74666-0836-4c1d-948a-4b34a8b90301\", \"name\": { \"fi\": \"Helsingin kaupunki\", \"sv\": \"Helsingfors stad\", \"en\": \"City of Helsinki\" } },{ \"id\": \"520a4492-cb78-498b-9c82-86504de88dce\", \"name\": { \"fi\": \"Espoon kaupunki\", \"sv\": \"Esbo stad\", \"en\": \"City of Espoo\" } },{ \"id\": \"6d78f89c-9fd7-41d9-84e0-4b78c0fa25ce\", \"name\": { \"fi\": \"Vantaan kaupunki\", \"sv\": \"Vanda stad\", \"en\": \"City of Vantaa\" } },{ \"id\": \"6f0458d4-42a3-434a-b9be-20c19fcfa5c3\", \"name\": { \"fi\": \"Kauniaisten kaupunki\", \"sv\": \"Grankulla stad\", \"en\": \"Town of Kauniainen\" } },{ \"id\": \"015fd5cd-b280-4d24-a5b4-0ba6ecb4c8a4\", \"name\": { \"fi\": \"Kirkkonummi\", \"sv\": \"Kyrkslätt\", \"en\": \"Kirkkonummi\" } },{ \"id\": \"0c8e4f99-3d52-47b9-84df-395716bd8b11\", \"name\": { \"fi\": \"Länsi-Uudenmaan hyvinvointialue\", \"sv\": \"Västra Nylands välfärdsområde\", \"en\": \"Western Uusimaa Wellbeing Services County\" } },{ \"id\": \"5de91045-92ab-484b-9f96-7010ff7fb35e\", \"name\": { \"fi\": \"Vantaan ja Keravan hyvinvointialue\", \"sv\": \"Vanda och Kervo välfärdsområde\", \"en\": \"Wellbeing services county of Vantaa and Kerava\" } }]" >> $GITHUB_ENV
        echo "SERVICE_MAP_URL=https://helsinki-maptiles.dev.hel.ninja/styles/hel-osm-bright-{language}/{z}/{x}/{y}{suffix}.png" >> $GITHUB_ENV
        echo "ACCESSIBLE_MAP_URL=https://helsinki-maptiles.dev.hel.ninja/styles/turku-osm-high-contrast-pattern-{language}/{z}/{x}/{y}{suffix}.png" >> $GITHUB_ENV
        echo "ORTOGRAPHIC_MAP_URL=https://kartta.hsy.fi/geoserver/gwc/service/wmts?layer=taustakartat_ja_aluejaot:Ortoilmakuva_2019&tilematrixset=ETRS-GK25&Service=WMTS&Request=GetTile&Version=1.0.0&TileMatrix=ETRS-GK25:{z}&TileCol={x}&TileRow={y}&Format=image/png" >> $GITHUB_ENV
        echo "ORTOGRAPHIC_WMS_URL=https://kartta.hsy.fi/geoserver/wms" >> $GITHUB_ENV
        echo "ORTOGRAPHIC_WMS_LAYER=taustakartat_ja_aluejaot:Ortoilmakuva_2019" >> $GITHUB_ENV
        echo "GUIDE_MAP_URL=https://kartta.hel.fi/ws/geoserver/avoindata/gwc/service/wmts?layer=avoindata:Karttasarja_PKS&tilematrixset=ETRS-GK25&Service=WMTS&Request=GetTile&Version=1.0.0&TileMatrix=ETRS-GK25:{z}&TileCol={x}&TileRow={y}&Format=image/png" >> $GITHUB_ENV
        echo "PLAIN_MAP_URL=https://mml-tiles.hel.ninja/avoin/wmts/1.0.0/selkokartta/default/ETRS-TM35FIN/{z}/{y}/{x}.png" >> $GITHUB_ENV
        echo "READ_FEEDBACK_URLS_HELSINKI=https://palautteet.hel.fi/fi/hae-palautteita#/app/search?r=12&text=,https://palautteet.hel.fi/sv/hae-palautteita#/app/search?r=12&text=,https://palautteet.hel.fi/en/hae-palautteita#/app/search?r=12&text=" >> $GITHUB_ENV
        echo "ADDITIONAL_FEEDBACK_URLS_ESPOO=https://easiointi.espoo.fi/eFeedback/fi,https://easiointi.espoo.fi/eFeedback/sv,https://easiointi.espoo.fi/eFeedback/en" >> $GITHUB_ENV
        echo "ADDITIONAL_FEEDBACK_URLS_KAUNIAINEN=https://www.kauniainen.fi/kaupunki-ja-paatoksenteko/osallistu-ja-vaikuta/,https://www.kauniainen.fi/sv/staden-och-beslutsfattande/delta-och-paverka/,https://www.kauniainen.fi/kaupunki-ja-paatoksenteko/osallistu-ja-vaikuta/" >> $GITHUB_ENV
        echo "ADDITIONAL_FEEDBACK_URLS_KIRKKONUMMI=https://kirkkonummi.fi/anna-palautetta-ja-vaikuta/,https://kyrkslatt.fi/ge-respons-och-paverka/,https://kirkkonummi.fi/anna-palautetta-ja-vaikuta/" >> $GITHUB_ENV
        echo "ADDITIONAL_FEEDBACK_URLS_VANTAA=https://www.vantaa.fi/fi/palaute,https://www.vantaa.fi/sv/feedback,https://www.vantaa.fi/en/feedback" >> $GITHUB_ENV
        echo "SLOW_FETCH_MESSAGE_TIMEOUT=3000" >> $GITHUB_ENV
        echo "HELSINKI_MAPTILES_ENABLED=true" >> $GITHUB_ENV

  e2e:
    needs: common
    runs-on: ubuntu-latest

    env:
      PORT: 2048
      SSR_FETCH_TIMEOUT: 2500
      ACCESSIBILITY_SENTENCE_API: https://www.hel.fi/palvelukarttaws/rest/v4
      SERVICEMAP_API: https://api.hel.fi/servicemap/
      SERVICEMAP_API_VERSION: "v2"
      EVENTS_API: https://api.hel.fi/linkedevents/v1
      RESERVATIONS_API: https://varaamo.hel.fi
      PRODUCTION_PREFIX: SM
      DIGITRANSIT_API: https://digitransit-proxy.api.hel.fi/routing/v1/routers/hsl/index/graphql
      FEEDBACK_URL: https://api.hel.fi/servicemap/open311/
      HEARING_MAP_API: https://kuulokuvat.fi/api/v1/servicemap-url
      MODE: production
      CITIES: helsinki,espoo,vantaa,kauniainen,kirkkonummi
      ORGANIZATIONS: '[{ "id": "83e74666-0836-4c1d-948a-4b34a8b90301", "name": { "fi": "Helsingin kaupunki", "sv": "Helsingfors stad", "en": "City of Helsinki" } },{ "id": "520a4492-cb78-498b-9c82-86504de88dce", "name": { "fi": "Espoon kaupunki", "sv": "Esbo stad", "en": "City of Espoo" } },{ "id": "6d78f89c-9fd7-41d9-84e0-4b78c0fa25ce", "name": { "fi": "Vantaan kaupunki", "sv": "Vanda stad", "en": "City of Vantaa" } },{ "id": "6f0458d4-42a3-434a-b9be-20c19fcfa5c3", "name": { "fi": "Kauniaisten kaupunki", "sv": "Grankulla stad", "en": "Town of Kauniainen" } },{ "id": "015fd5cd-b280-4d24-a5b4-0ba6ecb4c8a4", "name": { "fi": "Kirkkonummi", "sv": "Kyrkslätt", "en": "Kirkkonummi" } },{ "id": "0c8e4f99-3d52-47b9-84df-395716bd8b11", "name": { "fi": "Länsi-Uudenmaan hyvinvointialue", "sv": "Västra Nylands välfärdsområde", "en": "Western Uusimaa Wellbeing Services County" } },{ "id": "5de91045-92ab-484b-9f96-7010ff7fb35e", "name": { "fi": "Vantaan ja Keravan hyvinvointialue", "sv": "Vanda och Kervo välfärdsområde", "en": "Wellbeing services county of Vantaa and Kerava" } }]'
      SERVICE_MAP_URL: https://helsinki-maptiles.dev.hel.ninja/styles/hel-osm-bright-{language}/{z}/{x}/{y}{suffix}.png
      ACCESSIBLE_MAP_URL: https://helsinki-maptiles.dev.hel.ninja/styles/turku-osm-high-contrast-pattern-{language}/{z}/{x}/{y}{suffix}.png
      ORTOGRAPHIC_MAP_URL: https://kartta.hsy.fi/geoserver/gwc/service/wmts?layer=taustakartat_ja_aluejaot:Ortoilmakuva_2019&tilematrixset=ETRS-GK25&Service=WMTS&Request=GetTile&Version=1.0.0&TileMatrix=ETRS-GK25:{z}&TileCol={x}&TileRow={y}&Format=image%2Fpng
      ORTOGRAPHIC_WMS_URL: "https://kartta.hsy.fi/geoserver/wms"
      ORTOGRAPHIC_WMS_LAYER: "taustakartat_ja_aluejaot:Ortoilmakuva_2019"
      GUIDE_MAP_URL: https://kartta.hel.fi/ws/geoserver/avoindata/gwc/service/wmts?layer=avoindata:Karttasarja_PKS&tilematrixset=ETRS-GK25&Service=WMTS&Request=GetTile&Version=1.0.0&TileMatrix=ETRS-GK25:{z}&TileCol={x}&TileRow={y}&Format=image%2Fpng
      PLAIN_MAP_URL: https://mml-tiles.hel.ninja/avoin/wmts/1.0.0/selkokartta/default/ETRS-TM35FIN/{z}/{y}/{x}.png
      READ_FEEDBACK_URLS_HELSINKI: https://palautteet.hel.fi/fi/hae-palautteita#/app/search?r=12&text=,https://palautteet.hel.fi/sv/hae-palautteita#/app/search?r=12&text=,https://palautteet.hel.fi/en/hae-palautteita#/app/search?r=12&text=
      ADDITIONAL_FEEDBACK_URLS_ESPOO: https://easiointi.espoo.fi/eFeedback/fi,https://easiointi.espoo.fi/eFeedback/sv,https://easiointi.espoo.fi/eFeedback/en
      ADDITIONAL_FEEDBACK_URLS_KAUNIAINEN: https://www.kauniainen.fi/kaupunki-ja-paatoksenteko/osallistu-ja-vaikuta/,https://www.kauniainen.fi/sv/staden-och-beslutsfattande/delta-och-paverka/,https://www.kauniainen.fi/kaupunki-ja-paatoksenteko/osallistu-ja-vaikuta/
      ADDITIONAL_FEEDBACK_URLS_KIRKKONUMMI: https://kirkkonummi.fi/anna-palautetta-ja-vaikuta/,https://kyrkslatt.fi/ge-respons-och-paverka/,https://kirkkonummi.fi/anna-palautetta-ja-vaikuta/
      ADDITIONAL_FEEDBACK_URLS_VANTAA: https://www.vantaa.fi/fi/palaute,https://www.vantaa.fi/sv/feedback,https://www.vantaa.fi/en/feedback
      SLOW_FETCH_MESSAGE_TIMEOUT: 3000
      HELSINKI_MAPTILES_ENABLED: true

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build application
        run: yarn build
      - name: Install Playwright browsers
        run: yarn test:e2e:install
      - name: Run E2E tests
        run: yarn test:e2e
