# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PORT: 2048
      SSR_FETCH_TIMEOUT: 2500
      ACCESSIBILITY_SENTENCE_API: https://www.hel.fi/palvelukarttaws/rest/v4
      SERVICEMAP_API: https://api.hel.fi/servicemap/
      SERVICEMAP_API_VERSION: "v2"
      EVENTS_API: https://api.hel.fi/linkedevents/v1
      RESERVATIONS_API: https://api.hel.fi/respa/v1
      PRODUCTION_PREFIX: SM
      DIGITRANSIT_API: https://api.digitransit.fi/routing/v1/routers/hsl/index/graphql
      DIGITRANSIT_API_KEY: a9219bfb875d4cc79b5f69123b57d0db
      FEEDBACK_URL: https://api.hel.fi/servicemap/open311/
      HEARING_MAP_API: https://kuulokuvat.fi/api/v1/servicemap-url
      MODE: production
      CITIES: helsinki,espoo,vantaa,kauniainen,kirkkonummi
      ORGANIZATIONS: '[{ "id": "83e74666-0836-4c1d-948a-4b34a8b90301", "name": { "fi": "Helsingin kaupunki", "sv": "Helsingfors stad", "en": "City of Helsinki" } },{ "id": "520a4492-cb78-498b-9c82-86504de88dce", "name": { "fi": "Espoon kaupunki", "sv": "Esbo stad", "en": "City of Espoo" } },{ "id": "6d78f89c-9fd7-41d9-84e0-4b78c0fa25ce", "name": { "fi": "Vantaan kaupunki", "sv": "Vanda stad", "en": "City of Vantaa" } },{ "id": "6f0458d4-42a3-434a-b9be-20c19fcfa5c3", "name": { "fi": "Kauniaisten kaupunki", "sv": "Grankulla stad", "en": "Town of Kauniainen" } },{ "id": "015fd5cd-b280-4d24-a5b4-0ba6ecb4c8a4", "name": { "fi": "Kirkkonummi", "sv": "Kyrkslätt", "en": "Kirkkonummi" } },{ "id": "0c8e4f99-3d52-47b9-84df-395716bd8b11", "name": { "fi": "Länsi-Uudenmaan hyvinvointialue", "sv": "Västra Nylands välfärdsområde", "en": "Western Uusimaa Wellbeing Services County" } },{ "id": "5de91045-92ab-484b-9f96-7010ff7fb35e", "name": { "fi": "Vantaan ja Keravan hyvinvointialue", "sv": "Vanda och Kervo välfärdsområde", "en": "Wellbeing services county of Vantaa and Kerava" } }]'
      SERVICE_MAP_URL: https://tiles.hel.ninja/styles/hel-osm-bright/{z}/{x}/{y}
      ACCESSIBLE_MAP_URL: https://tiles.hel.ninja/styles/turku-osm-high-contrast-pattern/{z}/{x}/{y}
      ORTOGRAPHIC_MAP_URL: https://kartta.hsy.fi/geoserver/gwc/service/wmts?layer=taustakartat_ja_aluejaot:Ortoilmakuva_2019&tilematrixset=ETRS-GK25&Service=WMTS&Request=GetTile&Version=1.0.0&TileMatrix=ETRS-GK25:{z}&TileCol={x}&TileRow={y}&Format=image%2Fpng
      ORTOGRAPHIC_WMS_URL: "https://kartta.hsy.fi/geoserver/wms"
      ORTOGRAPHIC_WMS_LAYER: "taustakartat_ja_aluejaot:Ortoilmakuva_2019"
      GUIDE_MAP_URL: https://kartta.hel.fi/ws/geoserver/avoindata/gwc/service/wmts?layer=avoindata:Karttasarja_PKS&tilematrixset=ETRS-GK25&Service=WMTS&Request=GetTile&Version=1.0.0&TileMatrix=ETRS-GK25:{z}&TileCol={x}&TileRow={y}&Format=image%2Fpng
      PLAIN_MAP_URL: https://mml-tiles.hel.ninja/avoin/wmts/1.0.0/selkokartta/default/ETRS-TM35FIN/{z}/{y}/{x}.png
      READ_FEEDBACK_URLS_HELSINKI: https://palautteet.hel.fi/fi/hae-palautteita#/app/search?r=12&text=,https://palautteet.hel.fi/sv/hae-palautteita#/app/search?r=12&text=,https://palautteet.hel.fi/en/hae-palautteita#/app/search?r=12&text=
      ADDITIONAL_FEEDBACK_URLS_ESPOO: https://easiointi.espoo.fi/eFeedback/fi,https://easiointi.espoo.fi/eFeedback/sv,https://easiointi.espoo.fi/eFeedback/en
      ADDITIONAL_FEEDBACK_URLS_KAUNIAINEN: https://www.kauniainen.fi/kaupunki-ja-paatoksenteko/osallistu-ja-vaikuta/,https://www.kauniainen.fi/sv/staden-och-beslutsfattande/delta-och-paverka/,https://www.kauniainen.fi/kaupunki-ja-paatoksenteko/osallistu-ja-vaikuta/
      ADDITIONAL_FEEDBACK_URLS_KIRKKONUMMI: https://kirkkonummi.fi/anna-palautetta-ja-vaikuta/,https://kyrkslatt.fi/ge-respons-och-paverka/,https://kirkkonummi.fi/anna-palautetta-ja-vaikuta/
      ADDITIONAL_FEEDBACK_URLS_VANTAA: https://www.vantaa.fi/fi/palaute,https://www.vantaa.fi/sv/feedback,https://www.vantaa.fi/en/feedback
      SLOW_FETCH_MESSAGE_TIMEOUT: 3000

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --force
    - run: npm run testBuild
    - run: npm test
    - run: npm run browserTestCLI
